#!/usr/bin/env python3
"""
generate_import.py — Generate OpenTofu HCL + import blocks from an existing Slurm cluster.

Queries slurmrestd and writes four HCL files plus an imports file into the
output directory.  After running the script the workflow is:

  cd <output-dir>
  tofu init
  tofu apply        # import blocks pull Slurm state into OpenTofu state
  tofu apply        # reconcile: writes config-declared values back to Slurm
  tofu plan         # must be clean (no changes)

See the README in the same directory for full usage details.
"""

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from collections import defaultdict
from typing import Optional


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Built-in Slurm QOS that must not be destroyed via the REST API.
SYSTEM_QOS = {"normal"}

# Built-in accounts / users that are always present and should not be managed.
SYSTEM_ACCOUNTS = {"root"}
SYSTEM_USERS = {"root"}

HEADER = """\
# Generated by tools/generate_import/generate_import.py
# Do not edit by hand — re-run the script to regenerate.
#
# After 'tofu init':
#   tofu apply        # imports Slurm state into OpenTofu state
#   tofu apply        # reconcile: writes config values back to Slurm
#   tofu plan         # must show no changes
"""


# ---------------------------------------------------------------------------
# Slurm API client  (stdlib only — no third-party dependencies)
# ---------------------------------------------------------------------------

class SlurmClient:
    def __init__(self, endpoint: str, token: str, cluster: str, api_version: str):
        self.cluster = cluster
        self._base = f"{endpoint.rstrip('/')}/slurmdb/{api_version}"
        self._headers = {
            "X-SLURM-USER-TOKEN": token,
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

    def _get(self, path: str, params: Optional[dict] = None) -> dict:
        url = f"{self._base}/{path.lstrip('/')}"
        if params:
            qs = "&".join(f"{k}={v}" for k, v in params.items())
            url = f"{url}?{qs}"
        req = urllib.request.Request(url, headers=self._headers)
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read())
        except urllib.error.HTTPError as exc:
            body = exc.read().decode(errors="replace")
            raise SystemExit(f"Slurm API error {exc.code} on GET {url}:\n{body}") from exc
        except urllib.error.URLError as exc:
            raise SystemExit(f"Cannot reach slurmrestd at {url}: {exc.reason}") from exc

    def qos(self) -> list:
        return self._get("qos/").get("qos", [])

    def accounts(self) -> list:
        return self._get("accounts/").get("accounts", [])

    def associations(self) -> list:
        # Scope to the configured cluster so we don't pick up stale multi-cluster rows.
        return self._get("associations/", {"cluster": self.cluster}).get("associations", [])

    def users(self) -> list:
        return self._get("users/").get("users", [])


# ---------------------------------------------------------------------------
# Name sanitization
# ---------------------------------------------------------------------------

_name_registry: dict = {}   # rtype -> {tf_label: slurm_name}


def tf_label(slurm_name: str, rtype: str) -> str:
    """
    Convert a Slurm name to a valid Terraform resource label.

    Rules:
    - Replace any character outside [a-zA-Z0-9_] with _
    - If the result starts with a digit, prepend {rtype}_
    - Abort with a clear error on label collision.
    """
    label = re.sub(r"[^a-zA-Z0-9_]", "_", slurm_name)
    if label and label[0].isdigit():
        label = f"{rtype}_{label}"

    registry = _name_registry.setdefault(rtype, {})
    if label in registry and registry[label] != slurm_name:
        raise SystemExit(
            f"Name collision in {rtype}: Slurm names '{slurm_name}' and "
            f"'{registry[label]}' both map to Terraform label '{label}'.\n"
            f"Rename one of them in Slurm before running this script."
        )
    registry[label] = slurm_name
    return label


# ---------------------------------------------------------------------------
# HCL rendering helpers
# ---------------------------------------------------------------------------

def _q(s: str) -> str:
    """Double-quote an HCL string value."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _strlist(items: list) -> str:
    return "[" + ", ".join(_q(x) for x in items) + "]"


def _tres_list(tres: list) -> str:
    """Render a TRES list as an HCL list of inline objects."""
    parts = []
    for t in tres:
        fields = [f"type = {_q(t['type'])}"]
        if t.get("name"):
            fields.append(f"name = {_q(t['name'])}")
        fields.append(f"count = {t['count']}")
        parts.append("{ " + ", ".join(fields) + " }")
    return "[\n    " + ",\n    ".join(parts) + ",\n  ]"


def resource_block(rtype: str, label: str, attrs: list, comment: str = "") -> str:
    """
    Render a Terraform resource block.

    Each entry in attrs is a (key, value) tuple:
    - (key, str)  → emitted as  key = value
    - (text, None) → emitted verbatim (indented), used for nested blocks and
                     meta-arguments like depends_on.
    """
    lines = []
    if comment:
        lines.append(comment)
    lines.append(f'resource "{rtype}" "{label}" {{')
    for key, val in attrs:
        if val is None:
            for line in key.splitlines():
                lines.append(f"  {line}" if line.strip() else "")
        else:
            lines.append(f"  {key} = {val}")
    lines.append("}")
    return "\n".join(lines)


def import_block(rtype: str, label: str, slurm_id: str) -> str:
    return f'import {{\n  to = {rtype}.{label}\n  id = {_q(slurm_id)}\n}}'


# ---------------------------------------------------------------------------
# SlurmInt / SlurmFloat value extraction
# ---------------------------------------------------------------------------

def sint(obj) -> Optional[int]:
    """
    Extract a usable integer from a SlurmInt dict ({number, set, infinite}).
    Returns None for unset, infinite, or zero values (Slurm's "no limit").
    """
    if obj is None:
        return None
    if isinstance(obj, int):
        return obj if obj > 0 else None
    if isinstance(obj, dict):
        if obj.get("infinite") or not obj.get("set"):
            return None
        n = obj.get("number", 0)
        return n if n > 0 else None
    return None


def sfloat(obj) -> Optional[float]:
    """Extract a float from a SlurmFloat dict. Returns None if unset."""
    if obj is None:
        return None
    if isinstance(obj, (int, float)):
        return float(obj)
    if isinstance(obj, dict) and obj.get("set"):
        return float(obj.get("number", 0))
    return None


# ---------------------------------------------------------------------------
# TRES normalisation
# ---------------------------------------------------------------------------

def _norm_tres(raw) -> list:
    """
    Normalise a TRES list from the Slurm API into [{type, name?, count}].
    Skips entries with zero or unset counts.
    """
    if not raw:
        return []
    out = []
    for t in raw:
        if not isinstance(t, dict):
            continue
        raw_count = t.get("count", 0)
        count = sint(raw_count) if isinstance(raw_count, dict) else (int(raw_count) if raw_count else 0)
        if not count:
            continue
        entry: dict = {"type": t["type"], "count": count}
        if t.get("name"):
            entry["name"] = t["name"]
        out.append(entry)
    return out


# ---------------------------------------------------------------------------
# QOS generation
# ---------------------------------------------------------------------------

def _qos_attrs(q: dict) -> list:
    """Build the (key, value) attribute list for a slurm_qos resource block."""
    attrs = [("name", _q(q["name"]))]

    if q.get("description"):
        attrs.append(("description", _q(q["description"])))

    prio = sint(q.get("priority"))
    if prio:
        attrs.append(("priority", str(prio)))

    lim  = q.get("limits") or {}
    grace = lim.get("grace_time")
    if isinstance(grace, int) and grace > 0:
        attrs.append(("grace_time", str(grace)))

    mx = (lim.get("max") or {})

    # Wall-clock limits
    # limits.max.wall_clock.per.job  → max_wall_pj
    # limits.max.wall_clock.per.qos  → grp_wall
    wc_per = ((mx.get("wall_clock") or {}).get("per") or {})
    if v := sint(wc_per.get("job")):
        attrs.append(("max_wall_pj", str(v)))
    if v := sint(wc_per.get("qos")):
        attrs.append(("grp_wall", str(v)))

    # Job-count limits
    # limits.max.jobs.count                    → grp_submit_jobs
    # limits.max.jobs.per.user                 → max_jobs_per_user
    # limits.max.jobs.per.account              → max_jobs_per_account
    # limits.max.jobs.active_jobs.per.user     → max_submit_jobs_per_user
    # limits.max.jobs.active_jobs.per.account  → max_submit_jobs_per_account
    # limits.max.active_jobs.count             → grp_jobs
    jobs   = mx.get("jobs") or {}
    if v := sint(jobs.get("count")):
        attrs.append(("grp_submit_jobs", str(v)))
    j_per  = jobs.get("per") or {}
    if v := sint(j_per.get("user")):
        attrs.append(("max_jobs_per_user", str(v)))
    if v := sint(j_per.get("account")):
        attrs.append(("max_jobs_per_account", str(v)))
    aj_per = (jobs.get("active_jobs") or {}).get("per") or {}
    if v := sint(aj_per.get("user")):
        attrs.append(("max_submit_jobs_per_user", str(v)))
    if v := sint(aj_per.get("account")):
        attrs.append(("max_submit_jobs_per_account", str(v)))
    if v := sint((mx.get("active_jobs") or {}).get("count")):
        attrs.append(("grp_jobs", str(v)))

    # TRES limits
    # limits.max.tres.total              → grp_tres
    # limits.max.tres.minutes.total      → grp_tres_mins
    # limits.max.tres.per.job            → max_tres_per_job
    # limits.max.tres.per.node           → max_tres_per_node
    # limits.max.tres.per.user           → max_tres_per_user
    # limits.max.tres.per.account        → max_tres_per_account
    # limits.max.tres.minutes.per.job    → max_tres_mins_per_job
    # limits.max.tres.minutes.per.user   → max_tres_mins_per_user
    # limits.max.tres.minutes.per.account→ max_tres_mins_per_account
    # limits.min.tres.per.job            → min_tres_per_job
    tres      = mx.get("tres") or {}
    tres_per  = tres.get("per") or {}
    tres_mins = tres.get("minutes") or {}
    mins_per  = tres_mins.get("per") or {}

    for attr, raw in (
        ("grp_tres",               tres.get("total")),
        ("grp_tres_mins",          tres_mins.get("total")),
        ("max_tres_per_job",       tres_per.get("job")),
        ("max_tres_per_node",      tres_per.get("node")),
        ("max_tres_per_user",      tres_per.get("user")),
        ("max_tres_per_account",   tres_per.get("account")),
        ("max_tres_mins_per_job",  mins_per.get("job")),
        ("max_tres_mins_per_user", mins_per.get("user")),
        ("max_tres_mins_per_account", mins_per.get("account")),
    ):
        if entries := _norm_tres(raw):
            attrs.append((attr, _tres_list(entries)))

    mn_tres_per = ((lim.get("min") or {}).get("tres") or {}).get("per") or {}
    if entries := _norm_tres(mn_tres_per.get("job")):
        attrs.append(("min_tres_per_job", _tres_list(entries)))

    # Flags — skip empty / "NONE" sentinels
    flags = [f for f in (q.get("flags") or []) if f.upper() not in ("NONE", "")]
    if flags:
        attrs.append(("flags", _strlist(flags)))

    # Preemption
    preempt = q.get("preempt") or {}
    if plist := [x for x in (preempt.get("list") or []) if x]:
        attrs.append(("preempt_list", _strlist(plist)))
    if pmodes := [m.upper() for m in (preempt.get("mode") or [])
                  if m.upper() not in ("OFF", "NONE", "DISABLED", "")]:
        attrs.append(("preempt_mode", _strlist(pmodes)))
    if v := sint(preempt.get("exempt_time")):
        attrs.append(("preempt_exempt_time", str(v)))

    # Usage accounting
    uf = sfloat(q.get("usage_factor"))
    if uf is not None and abs(uf - 1.0) > 1e-9:
        attrs.append(("usage_factor", str(uf)))
    ut = sfloat(q.get("usage_threshold"))
    if ut is not None and ut != 0.0:
        attrs.append(("usage_threshold", str(ut)))

    return attrs


def generate_qos(qos_list: list) -> tuple:
    """Returns (hcl_content, import_blocks, warnings)."""
    warnings = []
    blocks   = []
    imports  = []

    for q in sorted(qos_list, key=lambda x: x["name"]):
        name  = q["name"]
        label = tf_label(name, "qos")
        is_system = name in SYSTEM_QOS

        if is_system:
            warnings.append(
                f"  QOS '{name}' is a built-in Slurm QOS (auto-created at DB init).\n"
                f"  It is included in the generated config but must NEVER be destroyed.\n"
                f"  To stop managing it: tofu state rm slurm_qos.{label}"
            )
            comment = (
                f"# WARNING: '{name}' is a built-in Slurm QOS created automatically at\n"
                f"# database initialisation. You can configure it via OpenTofu but you\n"
                f"# MUST NOT run 'tofu destroy' on this resource — deleting it via the\n"
                f"# REST API corrupts slurmdbd. To stop managing it without deleting it:\n"
                f"#   tofu state rm slurm_qos.{label}\n"
            )
        else:
            comment = ""

        blocks.append(resource_block("slurm_qos", label, _qos_attrs(q), comment))
        imports.append(import_block("slurm_qos", label, name))

    return "\n\n".join(blocks), imports, warnings


# ---------------------------------------------------------------------------
# Account generation
# ---------------------------------------------------------------------------

def _account_attrs(acc: dict, assoc: Optional[dict], label_map: dict,
                   root_qos: list) -> list:
    """Build the (key, value) attribute list for a slurm_account resource block."""
    attrs = [("name", _q(acc["name"]))]

    if desc := (acc.get("description") or ""):
        attrs.append(("description", _q(desc)))
    if org := (acc.get("organization") or ""):
        attrs.append(("organization", _q(org)))

    # parent_account is NOT returned by the /accounts/ endpoint; read it from
    # the account-level association (user="") which always carries it.
    parent = (assoc or {}).get("parent_account") or ""
    if parent and parent not in SYSTEM_ACCOUNTS:
        attrs.append(("parent_account", _q(parent)))

    if assoc:
        shares = assoc.get("shares_raw")
        # Skip fairshare <= 1: value of 1 is Slurm's default and indistinguishable
        # from "explicitly set to 1"; 0 means "inherit from parent".
        if isinstance(shares, int) and shares > 1:
            attrs.append(("fairshare", str(shares)))

        if dflt_qos := (assoc.get("default") or {}).get("qos") or "":
            attrs.append(("default_qos", _q(dflt_qos)))

        qos_list = sorted(x for x in (assoc.get("qos") or []) if x)
        # Skip allowed_qos when it matches the root association's default qos
        # list — those accounts have no explicit qos set and are just inheriting.
        if qos_list and qos_list != root_qos:
            attrs.append(("allowed_qos", _strlist(qos_list)))

        if v := sint((assoc.get("max") or {}).get("jobs", {}).get("active")):
            attrs.append(("max_jobs", str(v)))

    # depends_on — make child accounts wait for their parent to be created first.
    if parent and parent not in SYSTEM_ACCOUNTS and parent in label_map:
        attrs.append((f"depends_on = [slurm_account.{label_map[parent]}]", None))

    return attrs


def _account_depth(acc: dict, acc_by_name: dict) -> int:
    """Return the depth of an account in the hierarchy (root children = 0)."""
    depth, parent = 0, acc.get("parent_account") or ""
    visited: set = set()
    while parent and parent not in SYSTEM_ACCOUNTS and parent not in visited:
        visited.add(parent)
        parent_acc = acc_by_name.get(parent)
        if not parent_acc:
            break
        parent = parent_acc.get("parent_account") or ""
        depth += 1
    return depth


def generate_accounts(accounts: list, assocs: list) -> tuple:
    """Returns (hcl_content, import_blocks)."""
    # Account-level association lookup: account_name → assoc dict (user == "")
    acct_assoc: dict = {
        a["account"]: a
        for a in assocs
        if (a.get("user") == "" or a.get("user") is None) and a.get("account")
    }

    # Determine the root association's qos list — accounts that only have this
    # list set are inheriting it from root, not explicitly configuring it.
    root_assoc = acct_assoc.get("root") or {}
    root_qos   = sorted(x for x in (root_assoc.get("qos") or []) if x)

    # Pre-build the label map so _account_attrs can construct depends_on.
    # Use assoc parent_account (not the account object) for depth calculation.
    def acc_parent(name: str) -> str:
        return (acct_assoc.get(name) or {}).get("parent_account") or ""

    def depth(name: str) -> int:
        d, p, seen = 0, acc_parent(name), set()
        while p and p not in SYSTEM_ACCOUNTS and p not in seen:
            seen.add(p); p = acc_parent(p); d += 1
        return d

    label_map: dict = {
        a["name"]: tf_label(a["name"], "account")
        for a in accounts
        if a["name"] not in SYSTEM_ACCOUNTS
    }

    blocks  = []
    imports = []

    for acc in sorted(accounts, key=lambda a: (depth(a["name"]), a["name"])):
        name = acc["name"]
        if name in SYSTEM_ACCOUNTS:
            continue
        label = label_map[name]
        attrs = _account_attrs(acc, acct_assoc.get(name), label_map, root_qos)
        blocks.append(resource_block("slurm_account", label, attrs))
        imports.append(import_block("slurm_account", label, name))

    return "\n\n".join(blocks), imports


# ---------------------------------------------------------------------------
# User / association generation
# ---------------------------------------------------------------------------

def _assoc_block(a: dict, acct_qos: Optional[list] = None) -> str:
    """Render a single association {} nested block for a slurm_user resource."""
    lines = ["association {", f"  account = {_q(a['account'])}"]

    if partition := (a.get("partition") or ""):
        lines.append(f"  partition = {_q(partition)}")

    shares = a.get("shares_raw")
    if isinstance(shares, int) and shares > 1:
        lines.append(f"  fairshare = {shares}")

    if dflt_qos := (a.get("default") or {}).get("qos") or "":
        lines.append(f"  default_qos = {_q(dflt_qos)}")

    mx   = a.get("max") or {}
    jobs = mx.get("jobs") or {}
    per  = jobs.get("per") or {}

    # Job-count limits
    # max.jobs.active    → max_jobs
    # max.jobs.accruing  → max_jobs_accrue
    # max.jobs.total     → max_submit_jobs
    # max.jobs.per.count     → grp_jobs
    # max.jobs.per.accruing  → grp_jobs_accrue
    # max.jobs.per.submitted → grp_submit_jobs
    # max.jobs.per.wall_clock → max_wall_pj  (minutes)
    # max.per.account.wall_clock → grp_wall (minutes)
    for attr, obj in (
        ("max_jobs",        jobs.get("active")),
        ("max_jobs_accrue", jobs.get("accruing")),
        ("max_submit_jobs", jobs.get("total")),
        ("grp_jobs",        per.get("count")),
        ("grp_jobs_accrue", per.get("accruing")),
        ("grp_submit_jobs", per.get("submitted")),
        ("max_wall_pj",     per.get("wall_clock")),
    ):
        if v := sint(obj):
            lines.append(f"  {attr} = {v}")

    if v := sint(((mx.get("per") or {}).get("account") or {}).get("wall_clock")):
        lines.append(f"  grp_wall = {v}")

    if v := sint(a.get("priority")):
        lines.append(f"  priority = {v}")

    # TRES limits
    # max.tres.per.job         → max_tres_per_job
    # max.tres.per.node        → max_tres_per_node
    # max.tres.minutes.per.job → max_tres_mins_per_job
    # max.tres.total           → grp_tres
    # max.tres.group.minutes   → grp_tres_mins
    # max.tres.group.active    → grp_tres_run_mins
    tres      = mx.get("tres") or {}
    tres_per  = tres.get("per") or {}
    tres_mins = tres.get("minutes") or {}
    tres_grp  = tres.get("group") or {}

    for attr, raw in (
        ("max_tres_per_job",    tres_per.get("job")),
        ("max_tres_per_node",   tres_per.get("node")),
        ("max_tres_mins_per_job", (tres_mins.get("per") or {}).get("job")),
        ("grp_tres",            tres.get("total")),
        ("grp_tres_mins",       tres_grp.get("minutes")),
        ("grp_tres_run_mins",   tres_grp.get("active")),
    ):
        if entries := _norm_tres(raw):
            lines.append(f"  {attr} = {_tres_list(entries)}")

    # QOS list — only emit when explicitly set on this association and differs
    # from the parent account's effective list.  An empty list or a list that
    # matches the account's list means the user is just inheriting.
    qos_raw = [x for x in (a.get("qos") or []) if x]
    if qos_raw and sorted(qos_raw) != (acct_qos or []):
        lines.append(f"  qos = {_strlist(qos_raw)}")

    lines.append("}")
    return "\n".join(lines)


def generate_users(users: list, assocs: list) -> tuple:
    """Returns (hcl_content, import_blocks)."""
    # Account-level association lookup used to filter inherited QOS lists.
    acct_assoc: dict = {
        a["account"]: a
        for a in assocs
        if (a.get("user") == "" or a.get("user") is None) and a.get("account")
    }

    # Index user-level associations by username.
    user_assocs: dict = defaultdict(list)
    for a in assocs:
        user = a.get("user") or ""
        if user and user not in SYSTEM_USERS:
            user_assocs[user].append(a)

    blocks  = []
    imports = []

    for u in sorted(users, key=lambda x: x["name"]):
        name = u["name"]
        if name in SYSTEM_USERS:
            continue

        label = tf_label(name, "user")

        attrs: list = [("name", _q(name))]

        # administrator_level is a list; take the first element.
        admin_levels = u.get("administrator_level") or []
        admin = admin_levels[0] if admin_levels else ""
        if admin and admin.lower() not in ("none", ""):
            attrs.append(("admin_level", _q(admin)))

        default_acct = (u.get("default") or {}).get("account") or ""
        if default_acct:
            attrs.append(("default_account", _q(default_acct)))

        # One association block per user+account combination, sorted for
        # deterministic output.
        for a in sorted(user_assocs[name], key=lambda x: x.get("account", "")):
            account_name = a.get("account") or ""
            parent_assoc = acct_assoc.get(account_name) or {}
            account_qos  = sorted(x for x in (parent_assoc.get("qos") or []) if x)
            attrs.append((_assoc_block(a, account_qos), None))

        blocks.append(resource_block("slurm_user", label, attrs))
        imports.append(import_block("slurm_user", label, name))

    return "\n\n".join(blocks), imports


# ---------------------------------------------------------------------------
# provider.tf
# ---------------------------------------------------------------------------

def generate_provider(endpoint: str, cluster: str, api_version: str) -> str:
    return f"""\
terraform {{
  required_providers {{
    slurm = {{
      source  = "pescobar/slurm"
      version = "~> 0.1"
    }}
  }}
}}

variable "slurm_token" {{
  type      = string
  sensitive = true
}}

variable "slurm_api_version" {{
  type    = string
  default = {_q(api_version)}
}}

provider "slurm" {{
  endpoint    = {_q(endpoint)}
  token       = var.slurm_token
  cluster     = {_q(cluster)}
  api_version = var.slurm_api_version
}}
"""


# ---------------------------------------------------------------------------
# File writing
# ---------------------------------------------------------------------------

def write(path: str, content: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  wrote {path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Generate OpenTofu HCL + import blocks from a running Slurm cluster.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--endpoint",
        default=os.environ.get("SLURM_REST_URL", "http://localhost:6820"),
        help="slurmrestd base URL (env: SLURM_REST_URL)",
    )
    p.add_argument(
        "--token",
        default=os.environ.get("SLURM_JWT_TOKEN", ""),
        help="JWT token (env: SLURM_JWT_TOKEN)",
    )
    p.add_argument(
        "--cluster",
        default=os.environ.get("SLURM_CLUSTER", "linux"),
        help="Slurm cluster name (env: SLURM_CLUSTER)",
    )
    p.add_argument(
        "--api-version",
        default=os.environ.get("SLURM_API_VERSION", "v0.0.42"),
        help="slurmrestd API version (env: SLURM_API_VERSION)",
    )
    p.add_argument(
        "--output-dir",
        default="./generated",
        help="Directory to write the generated .tf files into",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()

    if not args.token:
        raise SystemExit(
            "No JWT token provided. Pass --token or set SLURM_JWT_TOKEN."
        )

    out = args.output_dir
    os.makedirs(out, exist_ok=True)

    client = SlurmClient(args.endpoint, args.token, args.cluster, args.api_version)

    print("Querying Slurm API...")
    print(f"  endpoint    : {args.endpoint}")
    print(f"  cluster     : {args.cluster}")
    print(f"  api-version : {args.api_version}")

    qos_list = client.qos()
    accounts = client.accounts()
    assocs   = client.associations()
    users    = client.users()

    print(f"  found {len(qos_list)} QOS, {len(accounts)} accounts, "
          f"{len(users)} users, {len(assocs)} associations")
    print()

    all_imports: list = []
    all_warnings: list = []

    # QOS
    qos_hcl, qos_imports, qos_warnings = generate_qos(qos_list)
    all_imports.extend(qos_imports)
    all_warnings.extend(qos_warnings)

    # Accounts
    acc_hcl, acc_imports = generate_accounts(accounts, assocs)
    all_imports.extend(acc_imports)

    # Users
    usr_hcl, usr_imports = generate_users(users, assocs)
    all_imports.extend(usr_imports)

    print(f"Generating {len(all_imports)} resources into {out}/")
    write(os.path.join(out, "provider.tf"),
          generate_provider(args.endpoint, args.cluster, args.api_version))
    write(os.path.join(out, "qos.tf"),
          HEADER + "\n" + qos_hcl + "\n")
    write(os.path.join(out, "accounts.tf"),
          HEADER + "\n" + acc_hcl + "\n")
    write(os.path.join(out, "users.tf"),
          HEADER + "\n" + usr_hcl + "\n")
    write(os.path.join(out, "imports.tf"),
          HEADER + "\n" + "\n\n".join(all_imports) + "\n")

    if all_warnings:
        print()
        print("WARNINGS:")
        for w in all_warnings:
            print(w)

    print()
    print("Done.  Next steps:")
    print(f"  cd {out}")
    print("  tofu init")
    print("  tofu apply        # imports Slurm state into OpenTofu state")
    print("  tofu apply        # reconcile: writes config values back to Slurm")
    print("  tofu plan         # must show no changes")


if __name__ == "__main__":
    main()
