#!/usr/bin/env python3
"""
generate_import.py — Generate OpenTofu HCL + import blocks from an existing Slurm cluster.

Queries slurmrestd and writes four HCL files plus an imports file into the
output directory.  After running the script the workflow is:

  cd <output-dir>
  tofu init
  tofu apply        # import blocks pull Slurm state into OpenTofu state
  tofu apply        # reconcile: writes config-declared values back to Slurm
  tofu plan         # must be clean (no changes)

See the README in the same directory for full usage details.
"""

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from collections import defaultdict
from typing import Optional


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Built-in Slurm QOS that must not be destroyed via the REST API.
SYSTEM_QOS = {"normal"}

# Built-in accounts / users that are always present and should not be managed.
SYSTEM_ACCOUNTS = {"root"}
SYSTEM_USERS = {"root"}

HEADER = """\
# Generated by tools/generate_import/generate_import.py
# Do not edit by hand — re-run the script to regenerate.
#
# After 'tofu init':
#   tofu apply        # imports Slurm state into OpenTofu state
#   tofu apply        # reconcile: writes config values back to Slurm
#   tofu plan         # must show no changes
"""


# ---------------------------------------------------------------------------
# Slurm API client  (stdlib only — no third-party dependencies)
# ---------------------------------------------------------------------------

class SlurmClient:
    def __init__(self, endpoint: str, token: str, cluster: str, api_version: str):
        self.cluster = cluster
        self._base = f"{endpoint.rstrip('/')}/slurmdb/{api_version}"
        self._headers = {
            "X-SLURM-USER-TOKEN": token,
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

    def _get(self, path: str, params: Optional[dict] = None) -> dict:
        url = f"{self._base}/{path.lstrip('/')}"
        if params:
            qs = "&".join(f"{k}={v}" for k, v in params.items())
            url = f"{url}?{qs}"
        req = urllib.request.Request(url, headers=self._headers)
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read())
        except urllib.error.HTTPError as exc:
            body = exc.read().decode(errors="replace")
            raise SystemExit(f"Slurm API error {exc.code} on GET {url}:\n{body}") from exc
        except urllib.error.URLError as exc:
            raise SystemExit(f"Cannot reach slurmrestd at {url}: {exc.reason}") from exc

    def qos(self) -> list:
        return self._get("qos/").get("qos", [])

    def accounts(self) -> list:
        return self._get("accounts/").get("accounts", [])

    def associations(self) -> list:
        # Scope to the configured cluster so we don't pick up stale multi-cluster rows.
        return self._get("associations/", {"cluster": self.cluster}).get("associations", [])

    def users(self) -> list:
        return self._get("users/").get("users", [])


# ---------------------------------------------------------------------------
# Name sanitization
# ---------------------------------------------------------------------------

_name_registry: dict = {}   # rtype -> {tf_label: slurm_name}


def tf_label(slurm_name: str, rtype: str) -> str:
    """
    Convert a Slurm name to a valid Terraform resource label.

    Rules:
    - Replace any character outside [a-zA-Z0-9_] with _
    - If the result starts with a digit, prepend {rtype}_
    - Abort with a clear error on label collision.
    """
    label = re.sub(r"[^a-zA-Z0-9_]", "_", slurm_name)
    if label and label[0].isdigit():
        label = f"{rtype}_{label}"

    registry = _name_registry.setdefault(rtype, {})
    if label in registry and registry[label] != slurm_name:
        raise SystemExit(
            f"Name collision in {rtype}: Slurm names '{slurm_name}' and "
            f"'{registry[label]}' both map to Terraform label '{label}'.\n"
            f"Rename one of them in Slurm before running this script."
        )
    registry[label] = slurm_name
    return label


# ---------------------------------------------------------------------------
# HCL rendering helpers
# ---------------------------------------------------------------------------

def _q(s: str) -> str:
    """Double-quote an HCL string value."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _strlist(items: list) -> str:
    return "[" + ", ".join(_q(x) for x in items) + "]"


def _tres_list(tres: list) -> str:
    """Render a TRES list as an HCL list of inline objects."""
    parts = []
    for t in tres:
        fields = [f"type = {_q(t['type'])}"]
        if t.get("name"):
            fields.append(f"name = {_q(t['name'])}")
        fields.append(f"count = {t['count']}")
        parts.append("{ " + ", ".join(fields) + " }")
    return "[\n    " + ",\n    ".join(parts) + ",\n  ]"


def _hcl_val(val) -> str:
    """
    Render a native Python value as an HCL right-hand side. Used by both the
    flat renderers below and (indirectly) as the single source of truth for how
    a field maps to HCL. Recognised kinds: bool, int, float, str, list-of-str,
    list-of-dict (TRES).
    """
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, int):
        return str(val)
    if isinstance(val, float):
        return repr(val)
    if isinstance(val, str):
        return _q(val)
    if isinstance(val, list):
        if val and isinstance(val[0], dict):
            return _tres_list(val)
        return _strlist(val)
    raise TypeError(f"cannot render HCL value of type {type(val).__name__}: {val!r}")


def resource_block(rtype: str, label: str, attrs: list, comment: str = "") -> str:
    """
    Render a Terraform resource block.

    Each entry in attrs is a (key, value) tuple:
    - (key, str)  → emitted as  key = value
    - (text, None) → emitted verbatim (indented), used for nested blocks and
                     meta-arguments like depends_on.
    """
    lines = []
    if comment:
        lines.append(comment)
    lines.append(f'resource "{rtype}" "{label}" {{')
    for key, val in attrs:
        if val is None:
            for line in key.splitlines():
                lines.append(f"  {line}" if line.strip() else "")
        else:
            lines.append(f"  {key} = {val}")
    lines.append("}")
    return "\n".join(lines)


def import_block(rtype: str, label: str, slurm_id: str) -> str:
    return f'import {{\n  to = {rtype}.{label}\n  id = {_q(slurm_id)}\n}}'


# ---------------------------------------------------------------------------
# SlurmInt / SlurmFloat value extraction
# ---------------------------------------------------------------------------

def sint(obj) -> Optional[int]:
    """
    Extract a usable integer from a SlurmInt dict ({number, set, infinite}).
    Returns None for unset, infinite, or zero values (Slurm's "no limit").
    """
    if obj is None:
        return None
    if isinstance(obj, int):
        return obj if obj > 0 else None
    if isinstance(obj, dict):
        if obj.get("infinite") or not obj.get("set"):
            return None
        n = obj.get("number", 0)
        return n if n > 0 else None
    return None


# Slurm stores fairshare=parent as shares_raw = INT32_MAX (SLURMDB_FS_USE_PARENT)
# and the REST API surfaces it as exactly that number, with no accompanying
# flag -- verified identical across Slurm 25.05 / 25.11 / 26.05. The provider's
# slurm_account / slurm_user fairshare attribute is a STRING for this reason: an
# integer weight, or the literal "parent".
FAIRSHARE_PARENT = 2147483647


def _fairshare_emit(shares) -> Optional[str]:
    """
    Map a raw shares_raw value to the string the provider's fairshare attribute
    expects, or None to skip emitting it:

      - INT32_MAX (SLURMDB_FS_USE_PARENT) -> "parent"
      - any weight > 1                    -> its decimal string
      - 0, 1, or non-int                  -> None (skip)

    Skipping <= 1 preserves existing behaviour: 1 is Slurm's default and
    indistinguishable from an explicit 1; 0 means "inherit from parent" and is
    likewise Slurm's own fallback, not declared intent.
    """
    if not isinstance(shares, int):
        return None
    if shares == FAIRSHARE_PARENT:
        return "parent"
    if shares > 1:
        return str(shares)
    return None


def sfloat(obj) -> Optional[float]:
    """Extract a float from a SlurmFloat dict. Returns None if unset."""
    if obj is None:
        return None
    if isinstance(obj, (int, float)):
        return float(obj)
    if isinstance(obj, dict) and obj.get("set"):
        return float(obj.get("number", 0))
    return None


# ---------------------------------------------------------------------------
# TRES normalisation
# ---------------------------------------------------------------------------

def _norm_tres(raw) -> list:
    """
    Normalise a TRES list from the Slurm API into [{type, name?, count}].
    Skips entries with zero or unset counts.
    """
    if not raw:
        return []
    out = []
    for t in raw:
        if not isinstance(t, dict):
            continue
        raw_count = t.get("count", 0)
        count = sint(raw_count) if isinstance(raw_count, dict) else (int(raw_count) if raw_count else 0)
        if not count:
            continue
        entry: dict = {"type": t["type"], "count": count}
        if t.get("name"):
            entry["name"] = t["name"]
        out.append(entry)
    return out


# ---------------------------------------------------------------------------
# QOS generation
# ---------------------------------------------------------------------------

def _qos_attrs(q: dict) -> list:
    """Build the (key, value) attribute list for a slurm_qos resource block."""
    attrs = [("name", _q(q["name"]))]

    if q.get("description"):
        attrs.append(("description", _q(q["description"])))

    prio = sint(q.get("priority"))
    if prio:
        attrs.append(("priority", str(prio)))

    lim  = q.get("limits") or {}
    grace = lim.get("grace_time")
    if isinstance(grace, int) and grace > 0:
        attrs.append(("grace_time", str(grace)))

    mx = (lim.get("max") or {})

    # Wall-clock limits
    # limits.max.wall_clock.per.job  → max_wall_pj
    # limits.max.wall_clock.per.qos  → grp_wall
    wc_per = ((mx.get("wall_clock") or {}).get("per") or {})
    if v := sint(wc_per.get("job")):
        attrs.append(("max_wall_pj", str(v)))
    if v := sint(wc_per.get("qos")):
        attrs.append(("grp_wall", str(v)))

    # Job-count limits
    # limits.max.jobs.count                    → grp_submit_jobs
    # limits.max.jobs.per.user                 → max_jobs_per_user
    # limits.max.jobs.per.account              → max_jobs_per_account
    # limits.max.jobs.active_jobs.per.user     → max_submit_jobs_per_user
    # limits.max.jobs.active_jobs.per.account  → max_submit_jobs_per_account
    # limits.max.active_jobs.count             → grp_jobs
    jobs   = mx.get("jobs") or {}
    if v := sint(jobs.get("count")):
        attrs.append(("grp_submit_jobs", str(v)))
    j_per  = jobs.get("per") or {}
    if v := sint(j_per.get("user")):
        attrs.append(("max_jobs_per_user", str(v)))
    if v := sint(j_per.get("account")):
        attrs.append(("max_jobs_per_account", str(v)))
    aj_per = (jobs.get("active_jobs") or {}).get("per") or {}
    if v := sint(aj_per.get("user")):
        attrs.append(("max_submit_jobs_per_user", str(v)))
    if v := sint(aj_per.get("account")):
        attrs.append(("max_submit_jobs_per_account", str(v)))
    if v := sint((mx.get("active_jobs") or {}).get("count")):
        attrs.append(("grp_jobs", str(v)))

    # TRES limits
    # limits.max.tres.total              → grp_tres
    # limits.max.tres.minutes.total      → grp_tres_mins
    # limits.max.tres.per.job            → max_tres_per_job
    # limits.max.tres.per.node           → max_tres_per_node
    # limits.max.tres.per.user           → max_tres_per_user
    # limits.max.tres.per.account        → max_tres_per_account
    # limits.max.tres.minutes.per.job    → max_tres_mins_per_job
    # limits.max.tres.minutes.per.user   → max_tres_mins_per_user
    # limits.max.tres.minutes.per.account→ max_tres_mins_per_account
    # limits.min.tres.per.job            → min_tres_per_job
    tres      = mx.get("tres") or {}
    tres_per  = tres.get("per") or {}
    tres_mins = tres.get("minutes") or {}
    mins_per  = tres_mins.get("per") or {}

    for attr, raw in (
        ("grp_tres",               tres.get("total")),
        ("grp_tres_mins",          tres_mins.get("total")),
        ("max_tres_per_job",       tres_per.get("job")),
        ("max_tres_per_node",      tres_per.get("node")),
        ("max_tres_per_user",      tres_per.get("user")),
        ("max_tres_per_account",   tres_per.get("account")),
        ("max_tres_mins_per_job",  mins_per.get("job")),
        ("max_tres_mins_per_user", mins_per.get("user")),
        ("max_tres_mins_per_account", mins_per.get("account")),
    ):
        if entries := _norm_tres(raw):
            attrs.append((attr, _tres_list(entries)))

    mn_tres_per = ((lim.get("min") or {}).get("tres") or {}).get("per") or {}
    if entries := _norm_tres(mn_tres_per.get("job")):
        attrs.append(("min_tres_per_job", _tres_list(entries)))

    # Flags — skip empty / "NONE" sentinels
    flags = [f for f in (q.get("flags") or []) if f.upper() not in ("NONE", "")]
    if flags:
        attrs.append(("flags", _strlist(flags)))

    # Preemption
    preempt = q.get("preempt") or {}
    if plist := [x for x in (preempt.get("list") or []) if x]:
        attrs.append(("preempt_list", _strlist(plist)))
    if pmodes := [m.upper() for m in (preempt.get("mode") or [])
                  if m.upper() not in ("OFF", "NONE", "DISABLED", "")]:
        attrs.append(("preempt_mode", _strlist(pmodes)))
    if v := sint(preempt.get("exempt_time")):
        attrs.append(("preempt_exempt_time", str(v)))

    # Usage accounting
    uf = sfloat(q.get("usage_factor"))
    if uf is not None and abs(uf - 1.0) > 1e-9:
        attrs.append(("usage_factor", str(uf)))
    ut = sfloat(q.get("usage_threshold"))
    if ut is not None and ut != 0.0:
        attrs.append(("usage_threshold", str(ut)))

    return attrs


def generate_qos(qos_list: list) -> tuple:
    """Returns (hcl_content, import_blocks, warnings)."""
    warnings = []
    blocks   = []
    imports  = []

    for q in sorted(qos_list, key=lambda x: x["name"]):
        name  = q["name"]
        label = tf_label(name, "qos")
        is_system = name in SYSTEM_QOS

        if is_system:
            warnings.append(
                f"  QOS '{name}' is a built-in Slurm QOS (auto-created at DB init).\n"
                f"  It is included in the generated config but must NEVER be destroyed.\n"
                f"  To stop managing it: tofu state rm slurm_qos.{label}"
            )
            comment = (
                f"# WARNING: '{name}' is a built-in Slurm QOS created automatically at\n"
                f"# database initialisation. You can configure it via OpenTofu but you\n"
                f"# MUST NOT run 'tofu destroy' on this resource — deleting it via the\n"
                f"# REST API corrupts slurmdbd. To stop managing it without deleting it:\n"
                f"#   tofu state rm slurm_qos.{label}\n"
            )
        else:
            comment = ""

        blocks.append(resource_block("slurm_qos", label, _qos_attrs(q), comment))
        imports.append(import_block("slurm_qos", label, name))

    return "\n\n".join(blocks), imports, warnings


# ---------------------------------------------------------------------------
# Account generation
# ---------------------------------------------------------------------------

def _account_fields(acc: dict, assoc: Optional[dict], root_qos: list) -> list:
    """
    Extract account attributes as native (key, value) pairs — the single source
    of truth shared by the flat (HCL) and big-cluster (YAML) emitters. Values
    are native ints / strs / lists (of str, or of TRES dicts). Excludes
    layout-specific bits (flat depends_on, big-cluster user_associations).
    """
    fields: list = [("name", acc["name"])]

    if desc := (acc.get("description") or ""):
        fields.append(("description", desc))
    # organization defaults to the account name in Slurm when not explicitly
    # set (verified against a live cluster: sacctmgr shows Organization ==
    # Account for an account created without one) -- skip it in that case,
    # same "indistinguishable from Slurm's own default" rule already applied
    # to fairshare below.
    org = acc.get("organization") or ""
    if org and org != acc["name"]:
        fields.append(("organization", org))

    # parent_account is NOT returned by the /accounts/ endpoint; read it from
    # the account-level association (user="") which always carries it.
    parent = (assoc or {}).get("parent_account") or ""
    if parent and parent not in SYSTEM_ACCOUNTS:
        fields.append(("parent_account", parent))

    if assoc:
        # fairshare emits "parent" for the INT32_MAX sentinel, a decimal string
        # for a real weight, or nothing for Slurm's own defaults -- see
        # _fairshare_emit().
        if (fs := _fairshare_emit(assoc.get("shares_raw"))) is not None:
            fields.append(("fairshare", fs))

        if dflt_qos := (assoc.get("default") or {}).get("qos") or "":
            fields.append(("default_qos", dflt_qos))

        qos_list = sorted(x for x in (assoc.get("qos") or []) if x)
        # Skip allowed_qos when it matches the root association's default qos
        # list — those accounts have no explicit qos set and are just inheriting.
        if qos_list and qos_list != root_qos:
            fields.append(("allowed_qos", qos_list))

        if v := sint((assoc.get("max") or {}).get("jobs", {}).get("active")):
            fields.append(("max_jobs", v))

        # TRES limits on the account-level association
        # max.tres.per.job         → max_tres_per_job
        # max.tres.per.node        → max_tres_per_node
        # max.tres.minutes.per.job → max_tres_mins_per_job
        # max.tres.total           → grp_tres
        # max.tres.group.minutes   → grp_tres_mins
        # max.tres.group.active    → grp_tres_run_mins
        mx        = assoc.get("max") or {}
        tres      = mx.get("tres") or {}
        tres_per  = tres.get("per") or {}
        tres_mins = tres.get("minutes") or {}
        tres_grp  = tres.get("group") or {}

        for attr, raw in (
            ("max_tres_per_job",    tres_per.get("job")),
            ("max_tres_per_node",   tres_per.get("node")),
            ("max_tres_mins_per_job", (tres_mins.get("per") or {}).get("job")),
            ("grp_tres",            tres.get("total")),
            ("grp_tres_mins",       tres_grp.get("minutes")),
            ("grp_tres_run_mins",   tres_grp.get("active")),
        ):
            if entries := _norm_tres(raw):
                fields.append((attr, entries))

    return fields


def _account_attrs(acc: dict, assoc: Optional[dict], label_map: dict,
                   root_qos: list) -> list:
    """Build the (key, value) attribute list for a slurm_account resource block."""
    attrs = [(key, _hcl_val(val)) for key, val in _account_fields(acc, assoc, root_qos)]

    # depends_on — make child accounts wait for their parent to be created first.
    parent = (assoc or {}).get("parent_account") or ""
    if parent and parent not in SYSTEM_ACCOUNTS and parent in label_map:
        attrs.append((f"depends_on = [slurm_account.{label_map[parent]}]", None))

    return attrs


def generate_accounts(accounts: list, assocs: list) -> tuple:
    """Returns (hcl_content, import_blocks)."""
    # Account-level association lookup: account_name → assoc dict (user == "")
    acct_assoc: dict = {
        a["account"]: a
        for a in assocs
        if (a.get("user") == "" or a.get("user") is None) and a.get("account")
    }

    # Determine the root association's qos list — accounts that only have this
    # list set are inheriting it from root, not explicitly configuring it.
    root_assoc = acct_assoc.get("root") or {}
    root_qos   = sorted(x for x in (root_assoc.get("qos") or []) if x)

    # Pre-build the label map so _account_attrs can construct depends_on.
    # Use assoc parent_account (not the account object) for depth calculation.
    def acc_parent(name: str) -> str:
        return (acct_assoc.get(name) or {}).get("parent_account") or ""

    def depth(name: str) -> int:
        d, p, seen = 0, acc_parent(name), set()
        while p and p not in SYSTEM_ACCOUNTS and p not in seen:
            seen.add(p); p = acc_parent(p); d += 1
        return d

    label_map: dict = {
        a["name"]: tf_label(a["name"], "account")
        for a in accounts
        if a["name"] not in SYSTEM_ACCOUNTS
    }

    blocks  = []
    imports = []

    for acc in sorted(accounts, key=lambda a: (depth(a["name"]), a["name"])):
        name = acc["name"]
        if name in SYSTEM_ACCOUNTS:
            continue
        label = label_map[name]
        attrs = _account_attrs(acc, acct_assoc.get(name), label_map, root_qos)
        blocks.append(resource_block("slurm_account", label, attrs))
        imports.append(import_block("slurm_account", label, name))

    return "\n\n".join(blocks), imports


# ---------------------------------------------------------------------------
# User / association generation
# ---------------------------------------------------------------------------

def _assoc_fields(a: dict, acct: Optional[dict] = None) -> list:
    """
    Extract a user↔account association's attributes as native (key, value)
    pairs, EXCLUDING the account itself. Single source of truth shared by the
    flat (HCL association block) and big-cluster (YAML member override) emitters.

    `acct` is the parent account-level association (user=""), used to detect
    values the user association is merely INHERITING rather than explicitly
    overriding. Empirically verified against a live cluster: Slurm's REST API
    resolves default_qos, max_jobs, max_tres_per_job, max_tres_per_node, and
    max_tres_mins_per_job to the account's own effective value even when the
    user's association never set them — there is no separate flag marking a
    value as inherited vs. explicit. A naive "emit whatever is non-zero"
    reading would therefore convert implicit inheritance into a permanent
    per-user pin, silently breaking future account-limit changes from
    propagating to that user. grp_tres / grp_tres_mins / grp_tres_run_mins
    do NOT inherit this way (also verified) and are always the association's
    own explicit value, so they are emitted unconditionally.
    """
    acct = acct or {}
    fields: list = []

    if partition := (a.get("partition") or ""):
        fields.append(("partition", partition))

    if (fs := _fairshare_emit(a.get("shares_raw"))) is not None:
        fields.append(("fairshare", fs))

    # default_qos — see inheritance note in the docstring.
    dflt_qos      = (a.get("default") or {}).get("qos") or ""
    acct_dflt_qos = (acct.get("default") or {}).get("qos") or ""
    if dflt_qos and dflt_qos != acct_dflt_qos:
        fields.append(("default_qos", dflt_qos))

    mx      = a.get("max") or {}
    jobs    = mx.get("jobs") or {}
    per     = jobs.get("per") or {}
    acct_mx = acct.get("max") or {}

    # max_jobs — see inheritance note in the docstring.
    # max.jobs.active → max_jobs
    acct_max_jobs = sint((acct_mx.get("jobs") or {}).get("active"))
    if v := sint(jobs.get("active")):
        if v != acct_max_jobs:
            fields.append(("max_jobs", v))

    # The remaining job-count / wall-clock limits below have no slurm_account
    # equivalent to inherit from in this provider's schema, so whatever Slurm
    # returns here is always the association's own explicit value.
    # max.jobs.accruing       → max_jobs_accrue
    # max.jobs.total          → max_submit_jobs
    # max.jobs.per.count      → grp_jobs
    # max.jobs.per.accruing   → grp_jobs_accrue
    # max.jobs.per.submitted  → grp_submit_jobs
    # max.jobs.per.wall_clock → max_wall_pj  (minutes)
    for attr, obj in (
        ("max_jobs_accrue", jobs.get("accruing")),
        ("max_submit_jobs", jobs.get("total")),
        ("grp_jobs",        per.get("count")),
        ("grp_jobs_accrue", per.get("accruing")),
        ("grp_submit_jobs", per.get("submitted")),
        ("max_wall_pj",     per.get("wall_clock")),
    ):
        if v := sint(obj):
            fields.append((attr, v))

    # max.per.account.wall_clock → grp_wall (minutes)
    if v := sint(((mx.get("per") or {}).get("account") or {}).get("wall_clock")):
        fields.append(("grp_wall", v))

    if v := sint(a.get("priority")):
        fields.append(("priority", v))

    # TRES limits
    # max.tres.per.job         → max_tres_per_job
    # max.tres.per.node        → max_tres_per_node
    # max.tres.minutes.per.job → max_tres_mins_per_job
    # max.tres.total           → grp_tres
    # max.tres.group.minutes   → grp_tres_mins
    # max.tres.group.active    → grp_tres_run_mins
    tres      = mx.get("tres") or {}
    tres_per  = tres.get("per") or {}
    tres_mins = tres.get("minutes") or {}
    tres_grp  = tres.get("group") or {}

    acct_tres      = acct_mx.get("tres") or {}
    acct_tres_per  = acct_tres.get("per") or {}
    acct_tres_mins = acct_tres.get("minutes") or {}

    # max_tres_per_job / max_tres_per_node / max_tres_mins_per_job — see
    # inheritance note in the docstring.
    for attr, raw, acct_raw in (
        ("max_tres_per_job", tres_per.get("job"), acct_tres_per.get("job")),
        ("max_tres_per_node", tres_per.get("node"), acct_tres_per.get("node")),
        ("max_tres_mins_per_job",
         (tres_mins.get("per") or {}).get("job"),
         (acct_tres_mins.get("per") or {}).get("job")),
    ):
        entries = _norm_tres(raw)
        if entries and entries != _norm_tres(acct_raw):
            fields.append((attr, entries))

    # grp_tres / grp_tres_mins / grp_tres_run_mins do not inherit — always
    # the association's own explicit value (see docstring).
    for attr, raw in (
        ("grp_tres",          tres.get("total")),
        ("grp_tres_mins",     tres_grp.get("minutes")),
        ("grp_tres_run_mins", tres_grp.get("active")),
    ):
        if entries := _norm_tres(raw):
            fields.append((attr, entries))

    # allowed_qos — only emit when explicitly set on this association and differs
    # from the parent account's effective list.  An empty list or a list that
    # matches the account's list means the user is just inheriting.
    # (a.get("qos") reads the raw Slurm API field, which is still named "qos" on
    # the wire; the output key is the provider's "allowed_qos" attribute name.)
    qos_raw  = [x for x in (a.get("qos") or []) if x]
    acct_qos = sorted(x for x in (acct.get("qos") or []) if x)
    if qos_raw and sorted(qos_raw) != acct_qos:
        fields.append(("allowed_qos", qos_raw))

    return fields


def _assoc_block(a: dict, acct: Optional[dict] = None) -> str:
    """Render a single association {} nested block for a slurm_user resource."""
    lines = ["association {", f"  account = {_q(a['account'])}"]
    for key, val in _assoc_fields(a, acct):
        lines.append(f"  {key} = {_hcl_val(val)}")
    lines.append("}")
    return "\n".join(lines)


def generate_users(users: list, assocs: list) -> tuple:
    """Returns (hcl_content, import_blocks, skipped)."""
    # Account-level association lookup used to filter inherited QOS lists.
    acct_assoc: dict = {
        a["account"]: a
        for a in assocs
        if (a.get("user") == "" or a.get("user") is None) and a.get("account")
    }

    # Index user-level associations by username.
    user_assocs: dict = defaultdict(list)
    for a in assocs:
        user = a.get("user") or ""
        if user and user not in SYSTEM_USERS:
            user_assocs[user].append(a)

    blocks   = []
    imports  = []
    skipped  = []

    for u in sorted(users, key=lambda x: x["name"]):
        name = u["name"]
        if name in SYSTEM_USERS:
            continue

        # A slurm_user resource requires default_account and at least one
        # association block -- both are impossible to populate for a user
        # with no associations at all (e.g. one left over from an
        # out-of-band failure partway through creation). Skip and warn
        # rather than emit HCL that fails validation, matching the
        # zero-association handling already in generate_bigcluster_users().
        if not user_assocs[name]:
            skipped.append(name)
            continue

        label = tf_label(name, "user")

        attrs: list = [("name", _q(name))]

        # administrator_level is a list; take the first element.
        admin_levels = u.get("administrator_level") or []
        admin = admin_levels[0] if admin_levels else ""
        if admin and admin.lower() not in ("none", ""):
            attrs.append(("admin_level", _q(admin)))

        # The Slurm REST API always returns default.account="" on the user
        # object (same bug the provider works around in its Read function).
        # Derive default_account from the association that has is_default=true.
        default_acct = next(
            (a.get("account", "") for a in user_assocs[name] if a.get("is_default")),
            "",
        )
        if default_acct:
            attrs.append(("default_account", _q(default_acct)))

        wckey = (u.get("default") or {}).get("wckey") or ""
        if wckey:
            attrs.append(("default_wc_key", _q(wckey)))

        # One association block per user+account combination, sorted for
        # deterministic output.
        for a in sorted(user_assocs[name], key=lambda x: x.get("account", "")):
            account_name = a.get("account") or ""
            parent_assoc = acct_assoc.get(account_name) or {}
            attrs.append((_assoc_block(a, parent_assoc), None))

        blocks.append(resource_block("slurm_user", label, attrs))
        imports.append(import_block("slurm_user", label, name))

    return "\n\n".join(blocks), imports, skipped


# ---------------------------------------------------------------------------
# Big-cluster layout  (account-centric YAML data + for_each generation)
#
# Emits a self-contained directory:
#   main.tf              provider config
#   qos.tf               QOS as plain HCL (same as flat)
#   generate.tf          locals + for_each that invert data/ into resources
#   data/accounts/*.yaml       one file per account: metadata + member list
#   data/users/admin_level.yaml      exceptions: non-default admin_level
#   data/users/default_accounts.yaml exceptions: multi-account default pins
#   data/users/wckeys.yaml           exceptions: pinned default_wc_key
#   imports.tf           import blocks targeting the for_each addresses
# ---------------------------------------------------------------------------

def import_block_indexed(rtype: str, base: str, key: str, slurm_id: str) -> str:
    """Import block targeting a for_each instance, e.g. slurm_account.this["x"]."""
    return f'import {{\n  to = {rtype}.{base}[{_q(key)}]\n  id = {_q(slurm_id)}\n}}'


def _safe_stem(name: str, used: dict) -> str:
    """
    Map a Slurm account name to a safe, unique YAML filename stem. The real name
    is preserved in the file's `name:` key, so the stem only needs to be a valid,
    collision-free filename (handles names with '/', spaces, etc.).
    """
    stem = re.sub(r"[^A-Za-z0-9._-]", "_", name)
    if not stem or stem in (".", ".."):
        stem = "account"
    base, n = stem, 1
    while stem in used and used[stem] != name:
        n += 1
        stem = f"{base}_{n}"
    used[stem] = name
    return stem


def _yaml_scalar(v) -> str:
    """Render a scalar for YAML. Strings are always double-quoted (robust)."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    return '"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _yaml_kv(key: str, val, indent: int = 0) -> str:
    """Render a `key: value` YAML line (or block for lists), matching our types."""
    pad = " " * indent
    if isinstance(val, list):
        if val and isinstance(val[0], dict):  # TRES list -> block of flow maps
            out = [f"{pad}{key}:"]
            for d in val:
                inner = ", ".join(f"{k}: {_yaml_scalar(vv)}" for k, vv in d.items())
                out.append(f"{pad}  - {{ {inner} }}")
            return "\n".join(out)
        inline = ", ".join(_yaml_scalar(x) for x in val)
        return f"{pad}{key}: [{inline}]"
    return f"{pad}{key}: {_yaml_scalar(val)}"


# Association fields that also exist on slurm_account. A value here
# OVERRIDES what the member would otherwise inherit from the account, so
# they render under the `account_overrides:` sub-key in the big-cluster
# YAML layout.
ACCOUNT_OVERRIDE_FIELDS = frozenset((
    "fairshare", "default_qos", "allowed_qos", "max_jobs",
    "max_tres_per_job", "max_tres_per_node", "max_tres_mins_per_job",
    "grp_tres", "grp_tres_mins", "grp_tres_run_mins",
))
# Everything else _assoc_fields() can return (partition, priority,
# max_jobs_accrue, max_submit_jobs, max_wall_pj, grp_jobs, grp_jobs_accrue,
# grp_submit_jobs, grp_wall) has no slurm_account equivalent at all -- those
# render under `association:` instead, since there is nothing to "override",
# only to declare for this specific user+account pairing.


def _render_account_yaml(fields: list, user_associations: list) -> str:
    """
    fields: [(key, native_value)] incl. name.
    user_associations: [(user, assoc_fields)] where assoc_fields is the flat
    (key, value) list _assoc_fields() returns, split here into the
    account_overrides / association sub-keys documented in README.md.
    """
    lines = ["# Generated by tools/generate_import/generate_import.py",
             "# Edit `user_associations` freely; re-running the tool overwrites this file."]
    for key, val in fields:
        lines.append(_yaml_kv(key, val))
    if user_associations:
        lines.append("user_associations:")
        for user, ofields in user_associations:
            if not ofields:
                lines.append(f"  - {_yaml_scalar(user)}")
                continue
            lines.append(f"  - user: {_yaml_scalar(user)}")
            overrides = [(k, v) for k, v in ofields if k in ACCOUNT_OVERRIDE_FIELDS]
            association = [(k, v) for k, v in ofields if k not in ACCOUNT_OVERRIDE_FIELDS]
            if overrides:
                lines.append("    account_overrides:")
                for k, v in overrides:
                    lines.append(_yaml_kv(k, v, indent=6))
            if association:
                lines.append("    association:")
                for k, v in association:
                    lines.append(_yaml_kv(k, v, indent=6))
    else:
        lines.append("user_associations: []")
    return "\n".join(lines) + "\n"


def _render_user_exception_file(header: list, exceptions: dict, key: str) -> str:
    """Render one flat `user: value` YAML file for a single exception key
    (admin_level, default_wc_key, or default_account) -- one concern per
    file, split out so each stays scannable as the cluster grows (see
    "data/users/ -- exceptions only" in examples/big-cluster/README.md)."""
    lines = list(header) + [""]
    entries = {u: info[key] for u, info in exceptions.items() if key in info}
    if not entries:
        lines.append("{}")
        return "\n".join(lines) + "\n"
    for user in sorted(entries):
        lines.append(f"{_yaml_scalar(user)}: {_yaml_scalar(entries[user])}")
    return "\n".join(lines) + "\n"


def _render_users_yaml_files(exceptions: dict) -> list:
    """Returns [(relpath, content)] for the three data/users/*.yaml files."""
    generated = ["# Generated by tools/generate_import/generate_import.py", "#"]
    return [
        (os.path.join("data", "users", "admin_level.yaml"), _render_user_exception_file(
            generated + [
                "# Exceptions only: users with a non-default admin_level (Operator or",
                "# Administrator). Everyone else is None and is NOT listed here.",
                "#",
                "# See https://slurm.schedmd.com/user_permissions.html for what each level",
                "# grants. The provider only supports admin_level today -- the separate,",
                "# per-account \"Coordinator\" role documented on that page is NOT",
                "# supported by this provider. See CLAUDE.md and README.md.",
            ], exceptions, "admin_level")),
        (os.path.join("data", "users", "default_accounts.yaml"), _render_user_exception_file(
            generated + [
                "# Exceptions only: users who belong to more than one account, pinning",
                "# which one is their login default_account. Single-account users are",
                "# NOT listed here -- their default account is derived automatically",
                "# from the one account file that lists them.",
            ], exceptions, "default_account")),
        (os.path.join("data", "users", "wckeys.yaml"), _render_user_exception_file(
            generated + [
                "# Exceptions only: users with a pinned default_wc_key.",
            ], exceptions, "default_wc_key")),
    ]


def generate_bigcluster_accounts(accounts: list, assocs: list) -> tuple:
    """Returns (files, import_blocks) where files is [(relpath, content)]."""
    acct_assoc: dict = {
        a["account"]: a
        for a in assocs
        if (a.get("user") == "" or a.get("user") is None) and a.get("account")
    }
    root_assoc = acct_assoc.get("root") or {}
    root_qos   = sorted(x for x in (root_assoc.get("qos") or []) if x)

    # Invert user-level associations into user_associations per account.
    user_associations_by_account: dict = defaultdict(list)
    for a in assocs:
        user = a.get("user") or ""
        if not user or user in SYSTEM_USERS:
            continue
        acct = a.get("account") or ""
        if not acct:
            continue
        parent_assoc = acct_assoc.get(acct) or {}
        user_associations_by_account[acct].append((user, _assoc_fields(a, parent_assoc)))

    files, imports, used = [], [], {}
    for acc in sorted(accounts, key=lambda a: a["name"]):
        name = acc["name"]
        if name in SYSTEM_ACCOUNTS:
            continue
        stem = _safe_stem(name, used)
        fields = _account_fields(acc, acct_assoc.get(name), root_qos)
        user_associations = sorted(
            user_associations_by_account.get(name, []), key=lambda m: m[0])
        files.append((os.path.join("data", "accounts", f"{stem}.yaml"),
                      _render_account_yaml(fields, user_associations)))
        imports.append(import_block_indexed("slurm_account", "this", stem, name))
    return files, imports


def generate_bigcluster_users(users: list, assocs: list) -> tuple:
    """Returns (exceptions, import_blocks, skipped) — exceptions is user→info."""
    user_assocs: dict = defaultdict(list)
    for a in assocs:
        u = a.get("user") or ""
        if u and u not in SYSTEM_USERS:
            user_assocs[u].append(a)

    exceptions: dict = {}
    imports: list = []
    skipped: list = []
    for u in sorted(users, key=lambda x: x["name"]):
        name = u["name"]
        if name in SYSTEM_USERS:
            continue
        alist = user_assocs.get(name, [])
        if not alist:
            # No associations => not a member of any account => cannot be
            # represented in the account-centric layout. Warn and skip.
            skipped.append(name)
            continue

        info: dict = {}
        admin_levels = u.get("administrator_level") or []
        admin = admin_levels[0] if admin_levels else ""
        if admin and admin.lower() not in ("none", ""):
            info["admin_level"] = admin
        wckey = (u.get("default") or {}).get("wckey") or ""
        if wckey:
            info["default_wc_key"] = wckey
        # Pin default_account only for multi-account users (single-account users
        # derive it unambiguously from their one account file).
        default_acct = next(
            (a.get("account", "") for a in alist if a.get("is_default")), "")
        if len(alist) > 1 and default_acct:
            info["default_account"] = default_acct

        if info:
            exceptions[name] = info
        imports.append(import_block_indexed("slurm_user", "this", name, name))
    return exceptions, imports, skipped


BIGCLUSTER_GENERATE_TF = '''\
# ---------------------------------------------------------------------------
# generate.tf — write once, rarely touched.
#
# Sysadmins edit the human-friendly, ACCOUNT-CENTRIC data under data/:
#   - data/accounts/<name>.yaml       : account metadata + its user_associations list
#   - data/users/admin_level.yaml     : ONLY users with a non-default admin_level
#   - data/users/default_accounts.yaml: ONLY multi-account users (login default pin)
#   - data/users/wckeys.yaml          : ONLY users with a pinned default_wc_key
#
# This file inverts that account-centric data into the USER-CENTRIC resources
# the Slurm provider requires (a slurm_user carries all of its associations).
# ---------------------------------------------------------------------------

locals {
  accounts_dir = "${path.module}/data/accounts"

  # Load every data/accounts/<stem>.yaml -> { "<stem>" = {…} }. The map key is
  # the filename stem; the real Slurm account name lives in the `name` key.
  accounts = {
    for f in fileset(local.accounts_dir, "*.yaml") :
    trimsuffix(f, ".yaml") => yamldecode(file("${local.accounts_dir}/${f}"))
  }

  # Per-user exceptions only, one file per concern -- everyone else is
  # derived automatically. Split into separate files (rather than one
  # data/users.yaml) so each stays small and scannable as the cluster grows:
  # skimming "who's an admin?" shouldn't require reading past every
  # multi-account user's default-account pin.
  admin_level_overrides     = yamldecode(file("${path.module}/data/users/admin_level.yaml"))
  default_account_overrides = yamldecode(file("${path.module}/data/users/default_accounts.yaml"))
  wckey_overrides           = yamldecode(file("${path.module}/data/users/wckeys.yaml"))

  # Flatten each account's user_associations into normalized association
  # tuples. An entry is either a bare string ("alice", no overrides) or an
  # object with two independent sub-maps -- try() handles both forms and
  # fills unset attributes with null:
  #
  #   account_overrides -- fields slurm_account also has (fairshare,
  #     default_qos, allowed_qos, max_jobs, TRES limits). Most of these
  #     inherit the account's value when omitted here (default_qos, max_jobs,
  #     max_tres_per_job, max_tres_per_node, max_tres_mins_per_job,
  #     allowed_qos); fairshare and grp_tres/grp_tres_mins/grp_tres_run_mins
  #     do NOT inherit -- Slurm falls back to its own fixed default instead.
  #     See "What an omitted account_overrides key resolves to" in README.md.
  #
  #   association -- fields that exist ONLY at the association level
  #     (partition, priority, job-count and wall-clock limits). There is no
  #     account-level equivalent to inherit from; these are declared here,
  #     not overridden.
  #
  # See "Account-level fields vs association-only fields" in README.md.
  memberships = flatten([
    for acct_key, acct in local.accounts : [
      for m in acct.user_associations : {
        account = try(acct.name, acct_key)
        user    = try(m.user, m)
        # account_overrides.*
        # fairshare is a string ("parent" or an integer weight); tostring()
        # accepts either a quoted or a bare-number value in the YAML.
        fairshare             = try(tostring(m.account_overrides.fairshare), null)
        default_qos           = try(m.account_overrides.default_qos, null)
        allowed_qos           = try(m.account_overrides.allowed_qos, null)
        max_jobs              = try(m.account_overrides.max_jobs, null)
        max_tres_per_job      = try(m.account_overrides.max_tres_per_job, null)
        max_tres_per_node     = try(m.account_overrides.max_tres_per_node, null)
        max_tres_mins_per_job = try(m.account_overrides.max_tres_mins_per_job, null)
        grp_tres              = try(m.account_overrides.grp_tres, null)
        grp_tres_mins         = try(m.account_overrides.grp_tres_mins, null)
        grp_tres_run_mins     = try(m.account_overrides.grp_tres_run_mins, null)
        # association.*
        partition       = try(m.association.partition, null)
        priority        = try(m.association.priority, null)
        max_jobs_accrue = try(m.association.max_jobs_accrue, null)
        max_submit_jobs = try(m.association.max_submit_jobs, null)
        max_wall_pj     = try(m.association.max_wall_pj, null)
        grp_jobs        = try(m.association.grp_jobs, null)
        grp_jobs_accrue = try(m.association.grp_jobs_accrue, null)
        grp_submit_jobs = try(m.association.grp_submit_jobs, null)
        grp_wall        = try(m.association.grp_wall, null)
      }
    ]
  ])

  # Invert: group memberships by user into the shape slurm_user needs.
  users = {
    for u in distinct([for m in local.memberships : m.user]) : u => {
      associations   = [for m in local.memberships : m if m.user == u]
      admin_level    = try(local.admin_level_overrides[u], null)
      default_wc_key = try(local.wckey_overrides[u], null)
      # Login default account: explicit override, else the user's (only) account.
      default_account = try(
        local.default_account_overrides[u],
        [for m in local.memberships : m.account if m.user == u][0],
      )
    }
  }
}

resource "slurm_account" "this" {
  for_each = local.accounts

  name           = try(each.value.name, each.key)
  description    = try(each.value.description, null)
  organization   = try(each.value.organization, null)
  parent_account = try(each.value.parent_account, null)
  fairshare      = try(tostring(each.value.fairshare), null)
  default_qos    = try(each.value.default_qos, null)
  allowed_qos    = try(each.value.allowed_qos, null)
  max_jobs       = try(each.value.max_jobs, null)

  max_tres_per_job      = try(each.value.max_tres_per_job, null)
  max_tres_per_node     = try(each.value.max_tres_per_node, null)
  max_tres_mins_per_job = try(each.value.max_tres_mins_per_job, null)
  grp_tres              = try(each.value.grp_tres, null)
  grp_tres_mins         = try(each.value.grp_tres_mins, null)
  grp_tres_run_mins     = try(each.value.grp_tres_run_mins, null){account_depends_on}
}

resource "slurm_user" "this" {
  for_each = local.users

  name            = each.key
  default_account = each.value.default_account
  admin_level     = each.value.admin_level
  default_wc_key  = each.value.default_wc_key

  dynamic "association" {
    for_each = each.value.associations
    content {
      account               = association.value.account
      partition             = association.value.partition
      fairshare             = association.value.fairshare
      priority              = association.value.priority
      default_qos           = association.value.default_qos
      allowed_qos           = association.value.allowed_qos
      max_jobs              = association.value.max_jobs
      max_jobs_accrue       = association.value.max_jobs_accrue
      max_submit_jobs       = association.value.max_submit_jobs
      max_wall_pj           = association.value.max_wall_pj
      grp_jobs              = association.value.grp_jobs
      grp_jobs_accrue       = association.value.grp_jobs_accrue
      grp_submit_jobs       = association.value.grp_submit_jobs
      grp_wall              = association.value.grp_wall
      max_tres_per_job      = association.value.max_tres_per_job
      max_tres_per_node     = association.value.max_tres_per_node
      max_tres_mins_per_job = association.value.max_tres_mins_per_job
      grp_tres              = association.value.grp_tres
      grp_tres_mins         = association.value.grp_tres_mins
      grp_tres_run_mins     = association.value.grp_tres_run_mins
    }
  }

  # Accounts (and transitively QOS) must exist before their associations.
  depends_on = [slurm_account.this]
}
'''


def generate_bigcluster_generate_tf(qos_labels: list) -> str:
    """Fill the generate.tf template, injecting the QOS depends_on for accounts."""
    if qos_labels:
        refs = ", ".join(f"slurm_qos.{lbl}" for lbl in qos_labels)
        dep = ("\n\n  # QOS referenced by name must exist before the accounts.\n"
               f"  depends_on = [{refs}]")
    else:
        dep = ""
    return BIGCLUSTER_GENERATE_TF.replace("{account_depends_on}", dep)


# ---------------------------------------------------------------------------
# provider.tf
# ---------------------------------------------------------------------------

def generate_provider(endpoint: str, cluster: str, api_version: str) -> str:
    return f"""\
terraform {{
  required_providers {{
    slurm = {{
      source  = "pescobar/slurm"
      version = "~> 0.1"
    }}
  }}
}}

variable "slurm_token" {{
  type      = string
  sensitive = true
}}

variable "slurm_api_version" {{
  type    = string
  default = {_q(api_version)}
}}

provider "slurm" {{
  endpoint    = {_q(endpoint)}
  token       = var.slurm_token
  cluster     = {_q(cluster)}
  api_version = var.slurm_api_version
}}
"""


# ---------------------------------------------------------------------------
# File writing
# ---------------------------------------------------------------------------

def write(path: str, content: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  wrote {path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Generate OpenTofu HCL + import blocks from a running Slurm cluster.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--endpoint",
        default=os.environ.get("SLURM_REST_URL", "http://localhost:6820"),
        help="slurmrestd base URL (env: SLURM_REST_URL)",
    )
    p.add_argument(
        "--token",
        default=os.environ.get("SLURM_JWT_TOKEN", ""),
        help="JWT token (env: SLURM_JWT_TOKEN)",
    )
    p.add_argument(
        "--cluster",
        default=os.environ.get("SLURM_CLUSTER", "linux"),
        help="Slurm cluster name (env: SLURM_CLUSTER)",
    )
    p.add_argument(
        "--api-version",
        default=os.environ.get("SLURM_API_VERSION", "v0.0.42"),
        help="slurmrestd API version (env: SLURM_API_VERSION)",
    )
    p.add_argument(
        "--output-dir",
        default="./generated",
        help="Directory to write the generated .tf files into",
    )
    p.add_argument(
        "--layout",
        choices=("flat", "big-cluster"),
        default="flat",
        help="Output layout: 'flat' (one HCL block per resource) or "
             "'big-cluster' (account-centric YAML data + for_each generation, "
             "recommended for large clusters)",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()

    if not args.token:
        raise SystemExit(
            "No JWT token provided. Pass --token or set SLURM_JWT_TOKEN."
        )

    out = args.output_dir
    os.makedirs(out, exist_ok=True)

    client = SlurmClient(args.endpoint, args.token, args.cluster, args.api_version)

    print("Querying Slurm API...")
    print(f"  endpoint    : {args.endpoint}")
    print(f"  cluster     : {args.cluster}")
    print(f"  api-version : {args.api_version}")

    qos_list = client.qos()
    accounts = client.accounts()
    assocs   = client.associations()
    users    = client.users()

    print(f"  found {len(qos_list)} QOS, {len(accounts)} accounts, "
          f"{len(users)} users, {len(assocs)} associations")
    print()

    all_imports: list = []
    all_warnings: list = []

    # QOS — identical HCL in both layouts.
    qos_hcl, qos_imports, qos_warnings = generate_qos(qos_list)
    all_imports.extend(qos_imports)
    all_warnings.extend(qos_warnings)

    if args.layout == "big-cluster":
        # QOS labels, recomputed for the accounts' depends_on (tf_label is
        # idempotent for an already-seen name).
        qos_labels = [tf_label(q["name"], "qos")
                      for q in sorted(qos_list, key=lambda x: x["name"])]

        account_files, acc_imports = generate_bigcluster_accounts(accounts, assocs)
        exceptions, usr_imports, skipped = generate_bigcluster_users(users, assocs)
        all_imports.extend(acc_imports)
        all_imports.extend(usr_imports)

        print(f"Generating {len(all_imports)} resources into {out}/ (big-cluster layout)")
        write(os.path.join(out, "main.tf"),
              generate_provider(args.endpoint, args.cluster, args.api_version))
        write(os.path.join(out, "qos.tf"), HEADER + "\n" + qos_hcl + "\n")
        write(os.path.join(out, "generate.tf"),
              generate_bigcluster_generate_tf(qos_labels))
        os.makedirs(os.path.join(out, "data", "accounts"), exist_ok=True)
        for relpath, content in account_files:
            write(os.path.join(out, relpath), content)
        os.makedirs(os.path.join(out, "data", "users"), exist_ok=True)
        for relpath, content in _render_users_yaml_files(exceptions):
            write(os.path.join(out, relpath), content)
        write(os.path.join(out, "imports.tf"),
              HEADER + "\n" + "\n\n".join(all_imports) + "\n")

        if skipped:
            all_warnings.append(
                f"  {len(skipped)} user(s) have no associations and cannot be\n"
                f"  represented in the account-centric layout — skipped:\n"
                f"    {', '.join(skipped[:20])}"
                + (" …" if len(skipped) > 20 else "")
            )
    else:
        # Accounts
        acc_hcl, acc_imports = generate_accounts(accounts, assocs)
        all_imports.extend(acc_imports)

        # Users
        usr_hcl, usr_imports, skipped = generate_users(users, assocs)
        all_imports.extend(usr_imports)

        print(f"Generating {len(all_imports)} resources into {out}/")
        write(os.path.join(out, "provider.tf"),
              generate_provider(args.endpoint, args.cluster, args.api_version))
        write(os.path.join(out, "qos.tf"),
              HEADER + "\n" + qos_hcl + "\n")
        write(os.path.join(out, "accounts.tf"),
              HEADER + "\n" + acc_hcl + "\n")
        write(os.path.join(out, "users.tf"),
              HEADER + "\n" + usr_hcl + "\n")
        write(os.path.join(out, "imports.tf"),
              HEADER + "\n" + "\n\n".join(all_imports) + "\n")

        if skipped:
            all_warnings.append(
                f"  {len(skipped)} user(s) have no associations and cannot be\n"
                f"  represented as a slurm_user resource (default_account and at\n"
                f"  least one association are both required) — skipped:\n"
                f"    {', '.join(skipped[:20])}"
                + (" …" if len(skipped) > 20 else "")
            )

    if all_warnings:
        print()
        print("WARNINGS:")
        for w in all_warnings:
            print(w)

    print()
    print("Done.  Next steps:")
    print(f"  cd {out}")
    print("  tofu init")
    print("  tofu apply        # imports Slurm state into OpenTofu state")
    print("  tofu apply        # reconcile: writes config values back to Slurm")
    print("  tofu plan         # must show no changes")


if __name__ == "__main__":
    main()
